### ISSUE TITLE
Send 404 for undefined rules.

### ISSUE THREAD

**Issue by Xender** [vfaronov/turq#10]
When accessing undefined paths, Turq responds with `200 OK` (and an empty response body).
I think it would be more intuitive and coherent with what webservers usually do if it responded with `404 Not Found` instead.

**Comment by vfaronov** [comment]
Thanks for the report, I think you’re right. I’m planning an overhaul of Turq in the coming weeks, will fix it there. In the meantime, the obvious workaround is to add `path().status(404).text('Not Found')` at the top of your rules.

**Comment by Xender** [comment]
[I've implemented it](https://github.com/Xender/turq/commit/5b16cc581fc8a8f3d52a7ff0c2d0adb60b1e41cf), seemed pretty straightforward.

Please tell me what do you think about it but maybe not yet merge, as I want to contribute some other things in the next few days (in particular, handling If-Modified-Since and what I believe is a cleaner way of using Turq programatically).

**Comment by vfaronov** [comment]
This diff is not quite right. For one, it breaks the [documented](https://turq.readthedocs.io/en/latest/#rules-structure) application of multiple rules to a single response. (This might even be a good thing, but then the docs need updating.) It may be cleaner to have a “default” rule _before_ that `for` loop.

But the point is, I’m looking into a complete rewrite of Turq soon. So I’m not sure it’s worthwhile to contribute code to the current version. I will be happy to hear your other suggestions (ideally in separate issues, or just [email me](mailto:vfaronov@gmail.com)) and maybe incorporate them in the rewrite.

That said, if you just need those changes right now in an “official” release of Turq, I can review and merge your PRs so you don’t have to wait for the rewrite.

**Comment by vfaronov** [comment]
Welp, this took more than a few weeks, but the new Turq is finally taking shape on the [overhaul](https://github.com/vfaronov/turq/tree/overhaul) branch, and I hope to release it soon as version 0.3.

However, this issue is not fixed there, because the new Turq does not separate routing from response definition like the old Turq does. Instead, the request path is checked only if and when desired:

```
if GET or HEAD:
    header('Vary', 'Accept-Encoding')
    if path == '/index.html':
        html()
        # ...and so on
```

So there is no obvious way for Turq to determine that a path does not exist.

Instead I simply make `error(404)` the default rules code — hopefully making it clear to the user that 404 is not automatic, it has to be written in the rules if needed.

With that, I’m inclined to close this issue. Do you have any other suggestions?

**Comment by vfaronov** [comment]
Released Turq 0.3.1 with the workaround explained above.
